### ISSUE TITLE
recfin_areas not working with rename_recfin

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [brianlangseth-NOAA/dataModerate_2021#5]
Im getting an error running the recfin scripts. Issue appears to be line 36 in rename_recfin. There the column_name = "DIST" but in recfin_areas, the column_name is set at "RECFIN_PORT_NAME".

**Comment by chantelwetzel-noaa** [comment]
The column_name is a function input with a default value that can be used on some data sets given area groupings (I am using it for CA data for copper), however, the default input can be changed based upon how you need to group areas given a particular data set.  Here are some alternative applications of these functions that do not group by "DIST":

or_recfin_len_data = rename_recfin(data = or_recfin_len, 
								   column_name = "State.Name",
								   area_grouping = list("Oregon"), 
								   area_names = "OR")

or_recfin_age_data = rename_recfin(data = or_recfin_age, 
								   column_name = "SAMPLING_AGENCY_NAME",
								   area_grouping = list("ODFW"), 
								   area_names = "OR")

You should be able to call the rename_recfin function using the "RECFIN_PORT_NAME" as long as you also provide the associated area_grouping and area_names for that data set.  The area_grouping will correspond to the names in the data set that you would like to group and the area_names will be a vector of names associated with the groupings.  A hypothetical example could be as follows:

rename_recfin(data = or_recfin_age, 
			column_name = "RECFIN_PORT_NAME",
			area_grouping = list(c("port_a", "port_b",) "port_c", "port_d"), 
			area_names = c("a_and_b", "c", "d"))
